validações:

histórico:

SELECT
    CLIENTE.NOME AS NOME_CLIENTE,
    CARRO.MODELO AS MODELO_CARRO,
    LOCACAO.DATA_LOCACAO,
    LOCACAO.DATA_DEVOLUCAO,
    LOCACAO.QUILOMETRAGEM_INICIAL,
    LOCACAO.QUILOMETRAGEM_FINAL,
    UNIDADE_LOCACAO.NOME AS UNIDADE_LOCACAO,
    UNIDADE_DEVOLUCAO.NOME AS UNIDADE_DEVOLUCAO
FROM
    LOCACAO
JOIN CLIENTE ON LOCACAO.FK_ID_CLIENTE = CLIENTE.ID
JOIN CARRO ON LOCACAO.FK_ID_CARRO = CARRO.ID
JOIN UNIDADE UNIDADE_LOCACAO ON LOCACAO.FK_ID_UNIDADE_LOCACAO = UNIDADE_LOCACAO.ID
LEFT JOIN UNIDADE UNIDADE_DEVOLUCAO ON LOCACAO.FK_ID_UNIDADE_DEVOLUCAO = UNIDADE_DEVOLUCAO.ID;

historico de quilometragem: 

SELECT
    CARRO.MODELO AS MODELO_CARRO,
    CARRO.QUILOMETRAGEM_ATUAL
FROM
    CARRO;
-- atualizando a quilometragem
UPDATE CARRO
SET QUILOMETRAGEM_ATUAL = (
    SELECT QUILOMETRAGEM_FINAL
    FROM LOCACAO
    WHERE LOCACAO.FK_ID_CARRO = CARRO.ID
      AND LOCACAO.DATA_DEVOLUCAO IS NOT NULL
    ORDER BY LOCACAO.DATA_DEVOLUCAO DESC
    LIMIT 1
);

-- Este select retorna os carros que estão atualmente locados (onde DATA_DEVOLUCAO é nula), juntamente com informações sobre o cliente que o locou. Se todos os carros estiverem com DATA_DEVOLUCAO preenchida (ou seja, nenhum carro está atualmente locado), o resultado será vazio.

SELECT CARRO.ID, CARRO.MODELO, CARRO.QUILOMETRAGEM_ATUAL, LOCACAO.DATA_LOCACAO, LOCACAO.DATA_DEVOLUCAO, CLIENTE.NOME AS NOME_CLIENTE
FROM CARRO
LEFT JOIN LOCACAO ON CARRO.ID = LOCACAO.FK_ID_CARRO
LEFT JOIN CLIENTE ON LOCACAO.FK_ID_CLIENTE = CLIENTE.ID
WHERE LOCACAO.DATA_DEVOLUCAO IS NULL;

